title: YAOB
description: Yet Another Opiniated Blog about modern life, with occasional interspersing of schizophrenic level pattern matching.
theme: minima
plugins:
  - jekyll-feed
url: "https://c4w1.github.io"
baseurl: ""
